# vim: set ft=ansible:
---
- name: Install and configure GitLab
  hosts: localhost
  connection: local
  gather_facts: False
  become: false
  tags:
    - "gitlab-play"
  vars:
    gitlab_hostname: "{{ lookup('env','GITLABHOSTNAME') }}"
  tasks:
    - name: Get root user token
      uri:
        url: 'http://{{gitlab_hostname}}/api/v3/session'
        body: 'login=root&password=password'
        method: POST
        status_code: 201
      register: root_token_out
      until: root_token_out|success
      retries: 3
      delay: 60

    - name: Create root token fact
      set_fact:
        root_token: '{{root_token_out.json.private_token}}'

    - name: Create GitLab users
      include: create_gitlab_users.yml
      with_sequence: start=0 end=50 format=user%02g
      tags:
        - "gitlab-create-users"

    - name: Import GitLab repos
      include: import_gitlab_repos.yml
      with_sequence: start=0 end=50 format=user%02g
      tags:
        - "gitlab-import-repos"
